spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081
